# Generated by Django 2.2 on 2021-06-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_post_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_food', models.CharField(max_length=255)),
                ('appetizer', models.CharField(max_length=255)),
                ('main_course', models.CharField(max_length=255)),
                ('dessert', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ManyToManyField(related_name='food', to='login_app.User')),
            ],
        ),
    ]
